names = ('pier', 'dumac', 'edgar')
print (names[0])
print (names[1])
print (names[2])
message = "Hello " + (names[0])
print (message)
message = "Hello " + (names[1])
print (message)
message = "Hello " + (names[2])
print (message)
