List = ('car', 'bike', 'jet')
message = 'I would like to own a ' + (List[0])
print (message)
message = 'I would like to own a ' + (List[1])
print (message)
message = 'I would like to own a ' + (List[2])
print (message)
